### ISSUE TITLE
Could you store config file in `~/.kube` or `~/.config` instead?

### ISSUE THREAD

**Issue by applejag** [Telemaco019/kubesafe#1]
Hello! I don't like having too many dotfiles in my home directory.

I see that you only read the config from `~/.kubesafe.yaml`:

https://github.com/Telemaco019/kubesafe/blob/3406ce756969374ea6faf12c2004581fa3afcbad/internal/repositories/repository.go#L34-L43

Could you change it to instead store it in the `~/.kube` directory? Such as `~/.kube/kubesafe.yaml`

To not break compatibility, your tool could look if `~/.kubesafe.yaml` already exists, and then use that first and foremost. But then otherwise default to `~/.kube/kubesafe.yaml`

**Comment by Telemaco019** [comment]
My bad, I started with the home directory for simplicity and then forgot to switch it to `~/.kube` 😅.

In the next release, I'll set `~/.kube` as the default path for the settings file, with the home directory as a fallback for backward compatibility.

Thanks a lot for catching that!

**Comment by chicks-net** [comment]
There is also the [XDG standard](https://specifications.freedesktop.org/basedir-spec/latest/) for home directory config files.  [This article](https://alchemists.io/articles/xdg_base_directory_specification#:~:text=The%20XDG%20Base%20Directory%20Specification,across%20different%20programs%20and%20desktops.) gives a gentle intro to the standard.

**Comment by Telemaco019** [comment]
> There is also the [XDG standard](https://specifications.freedesktop.org/basedir-spec/latest/) for home directory config files. [This article](https://alchemists.io/articles/xdg_base_directory_specification#:~:text=The%20XDG%20Base%20Directory%20Specification,across%20different%20programs%20and%20desktops.) gives a gentle intro to the standard.

That's interesting, thanks for sharing it @chicks-net!

**Comment by Telemaco019** [comment]
Kubesafe now follows the XDG standard, as highlighted by @chicks-net. For backward compatibility, it first checks for the old file at `~/.kubesafe.yaml`. If not found, it defaults to the new path: `~/.config/kubesafe/config.yaml`.

**Comment by applejag** [comment]
Btw in Go there's the os.ConfigDir which has better crossplatform support. Such as XDG config on Linux, AppData on Windows, etc.

**Comment by Telemaco019** [comment]
That's even better, thanks for the heads up @applejag! I've just refactored it using `os.ConfigDir`, so now the path `~/.config/kubesafe` is used only for UNIX systems.
