### ISSUE TITLE
Recognize all contexts in $KUBECONFIG env variable

### ISSUE THREAD

**Issue by artntek** [Telemaco019/kubesafe#11]
I think it's standard to have multiple k8s config files and include the paths of those in the `$KUBECONFIG` env variable. The ability to read contexts from all the configs included in this env var would be an awesome addition to kubesafe!

I see from the code that KS only reads the contexts in the `~/.kube/config` file, so if I try to `kubesafe context add` a context that's in another config file, I get an error (context is not available).

(As a workaround, I noticed if you add contexts using regular expressions, they are not checked against the available contexts, so that works OK)

Thanks, and keep up the good work!

**Comment by Telemaco019** [comment]
Hey @artntek, thanks for the suggestion! Good point, the config path should be read from the `$KUBECONFIG` env variable. I'll implement this soon!
