### ISSUE TITLE
Configure "protected contexts" / "safe contexts" via regex

### ISSUE THREAD

**Issue by applejag** [Telemaco019/kubesafe#2]
Hello!

Really enticing tool! Would it be possible to add support for regex-based matching?

At our workplace we have a lot of clusters, and they follow a very consistent naming convention. Such as all production clusters starting with `prod-...`

For example:

```bash
kubesafe context add --regex '^prod-'
```

**Comment by Telemaco019** [comment]
Hi @applejag, great idea, thanks for the suggestion! I'll definitely include it in the next release ;)
