### ISSUE TITLE
scripted configuration

### ISSUE THREAD

**Issue by rophy** [Telemaco019/kubesafe#8]
hi, great tool that has lots of potential!

Currently `kubesafe context add <context_name>` requires user to interactively select commands.

It would be ideal if this can be fully scripted.

**Comment by Telemaco019** [comment]
Thanks for the feedback, @rophy! I agree, that’s also particularly useful when using kubectl plugins or other tools with custom commands. I'll definitely include this in one of the next releases 👍

**Comment by Telemaco019** [comment]
Hi @rophy, you can now provide safe commands just like this:

```shell
kubesafe context add my-context --commands "delete,apply,upgdrade"
```

I'll release this feature in v0.2.0 later today. Thanks again!
